version: "3"

services:
  editor:
    image: squidfunk/mkdocs-material
    ports:
      - 3031:8000
    command: "serve -a 0.0.0.0:8000 "
    working_dir: /app/
    volumes:
      - /home/pascal/mkdocs:/app
  production:
    image: squidfunk/mkdocs-material
    user: 1000:1000
    entrypoint: "/bin/sh -c"
    command: >
      "sed 's/site_url:.*/site_url: \"\"/ ' mkdocs.yml > mkdocs.prod.yml && 
             mkdocs build --config-file mkdocs.prod.yml"
    working_dir: /app/
    volumes:
      - /home/pascal/mkdocs:/app
  vscode:
    image: codercom/code-server
    command: "--auth none"
    user: "1000:1000"
    ports:
      - 3033:8080
    volumes:
      - /home/pascal/mkdocs/:/home/coder/project:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pascal/mkdocs/entrypoint.d:/entrypoint.d
  slides:
    image: mcr.microsoft.com/playwright:focal
    entrypoint: "/bin/sh -c"
    command: >
      "while [ ! -f /app/site/index.html ]; do sleep 1; done && 
      yarn install &&
      find -type f -name slides.md -exec bash -c \"yarn slidev build {} --out `pwd`/site/\\\$(basename \\\$(dirname {}))\" \\\; "
    working_dir: /app/
    depends_on:
      - production
    volumes:
      - /home/pascal/mkdocs:/app
  leanote:
    image: docker.io/netpascal0123/leanote:markdown
    volumes:
      - /home/pascal/mkdocs/docs:/leanote/docs
    ports:
      - 9000:9000
